[package]
  name = "fireluau/ohmyprvd-obby"
  version = "0.1.0"
  registry = "https://github.com/UpliftGames/wally-index"
  realm = "shared"

[dependencies]
  Fusion = "plainsour/lemon@0.3.0-dev.5.9"
  prvd = "znotfireman/ohmyprvd@0.1.1-alpha"
  t = "osyrisrblx/t@3.1.1"
